Allow OpenOCD to return hex formatted values
OpenOCD may return hex values from mem2array or mrw, so allow those.

mem2array output:
0 0xb8 1 0xba 2 0xc 3 0x0 4 0xb8 5 0xba

This might depend on the particular adapter driver being used but
parsing either is more robust. The problem was observed with OpenOCD
0.12.0 and cmsis-dap.

Failed with:

cargo xtask humility app/.../recovery.toml -- tasks
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.09s
     Running `target/debug/xtask humility app/.../recovery.toml -- tasks`
humility: attached via OpenOCD
humility tasks failed: failed to read image ID at 0xcaec0; board mismatch?

Caused by:
    invalid digit found in string
Error: humility failed